version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14 # Specify the Node.js version you want to use
    commands:
      - npm install # Install project dependencies

  build:
    commands:
      - npm run build # Replace with your build script if needed
      - npm test # Run tests if applicable

artifacts:
  files:
    - '**/*' # Include all files in the build artifact

